spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mp?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
logging:
  level:
    root: info
    com.bdqn.mp.dao: trace #日志级别最低的
  pattern:
    console: '%p%m%n' #日志格式
mybatis-plus:
  mapper-locations: mapper/*.xml #本地xml存放位置
  global-config:
    db-config:
      id-type: id_worker #全局主键策略
      table-prefix: tt_ #表明前缀
      table-underline: true #默认为下划线
      #field-strategy: ignored  # ignored会将全部字段显示出来，如果更新的话，字段值可能赋值为null, 有风险，一般不做此配置
#      field-strategy: not_empty # not_empty将 空字符串和空值都会忽略
#      field-strategy: not_null # not_empty将 空值都会忽略, 一般全局和局部配合使用,局部优于全局
  #type-aliases-package: com.bdqn.mp.pojo #别名配置
  #config-location: classpath*:mybatis/*.xml  #核心配置文件,因为maven多模块项目的扫描需要以classpath*开头（即加载多个jar包下的XML文件）
  #configuration: #configuration的配置和config-location不能同时出现
    #map-underscore-to-camel-case: true #驼峰转下划线
server:
  servlet:
    context-path: /mp
  port: 8080
#自定义配置
#limit:
#  minMoney: 1
#  maxMoney: 99999
#  description:  最少要发${limit.minMoney}元,最多要发${limit.maxMoney}元